/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "contractor" CASCADE;

DROP TABLE IF EXISTS "temporary_employee" CASCADE;

DROP TABLE IF EXISTS "permanent_employee" CASCADE;

CREATE TABLE "permanent_employee" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "id" BIGSERIAL NOT NULL PRIMARY KEY);

CREATE TABLE "temporary_employee" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "duration" BIGINT NOT NULL);

CREATE TABLE "contractor" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "email" TEXT NOT NULL PRIMARY KEY);

