/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "contractor" CASCADE;

DROP TABLE IF EXISTS "employee" CASCADE;

DROP TABLE IF EXISTS "person" CASCADE;

CREATE TABLE "person" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "typeid" TEXT NOT NULL,
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL);

CREATE TABLE "employee" (
  "id" BIGINT NOT NULL PRIMARY KEY,
  "temporary" BOOLEAN NOT NULL,
  CONSTRAINT "id_fk"
    FOREIGN KEY ("id")
    REFERENCES "person" ("id")
    ON DELETE CASCADE);

CREATE TABLE "contractor" (
  "id" BIGINT NOT NULL PRIMARY KEY,
  "email" TEXT NOT NULL,
  CONSTRAINT "id_fk"
    FOREIGN KEY ("id")
    REFERENCES "person" ("id")
    ON DELETE CASCADE);

