/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "employee_projects" CASCADE;

DROP TABLE IF EXISTS "employee" CASCADE;

DROP TABLE IF EXISTS "project" CASCADE;

DROP TABLE IF EXISTS "position" CASCADE;

DROP TABLE IF EXISTS "employer" CASCADE;

CREATE TABLE "employer" (
  "name" TEXT NOT NULL PRIMARY KEY);

CREATE TABLE "position" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL);

CREATE TABLE "project" (
  "name" TEXT NOT NULL PRIMARY KEY);

CREATE TABLE "employee" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "employer" TEXT NOT NULL,
  "position" BIGINT NOT NULL,
  CONSTRAINT "employer_fk"
    FOREIGN KEY ("employer")
    REFERENCES "employer" ("name")
    INITIALLY DEFERRED,
  CONSTRAINT "position_fk"
    FOREIGN KEY ("position")
    REFERENCES "position" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "employee_projects" (
  "object_id" BIGINT NOT NULL,
  "value" TEXT NOT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "employee" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "value_fk"
    FOREIGN KEY ("value")
    REFERENCES "project" ("name")
    INITIALLY DEFERRED);

CREATE INDEX "employee_projects_object_id_i"
  ON "employee_projects" ("object_id");

