/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "EmployeeDegree" CASCADE;

DROP TABLE IF EXISTS "Employee" CASCADE;

DROP TABLE IF EXISTS "Employer" CASCADE;

CREATE TABLE "Employer" (
  "name" VARCHAR(255) NOT NULL PRIMARY KEY);

CREATE TABLE "Employee" (
  "ssn" INTEGER NOT NULL PRIMARY KEY,
  "first_name" VARCHAR(255) NOT NULL,
  "last_name" VARCHAR(255) NOT NULL,
  "employer" VARCHAR(255) NOT NULL,
  CONSTRAINT "employer_fk"
    FOREIGN KEY ("employer")
    REFERENCES "Employer" ("name")
    INITIALLY DEFERRED);

CREATE TABLE "EmployeeDegree" (
  "ssn" INTEGER NOT NULL,
  "degree" VARCHAR(255) NOT NULL,
  CONSTRAINT "ssn_fk"
    FOREIGN KEY ("ssn")
    REFERENCES "Employee" ("ssn")
    ON DELETE CASCADE);

CREATE INDEX "EmployeeDegree_ssn_i"
  ON "EmployeeDegree" ("ssn");

